### PR TITLE
Export AppHolder

### PR DESCRIPTION
**Pull request by tovbinm**
This change also requires modifying `@frontegg/js`:
```patch
diff --git a/node_modules/@frontegg/react/index.js b/node_modules/@frontegg/react/index.js
index d2199a7..abfb09d 100644
--- a/node_modules/@frontegg/react/index.js
+++ b/node_modules/@frontegg/react/index.js
@@ -239,4 +239,5 @@ exports.Connector = Connector;
 exports.ConnectorHistory = ConnectorHistory;
 exports.FronteggProvider = FronteggProvider;
 exports.useCheckoutDialog = useCheckoutDialog;
+exports.AppHolder = AppHolder.AppHolder;
 //# sourceMappingURL=index.js.map
```

Where can I modify it?

### CODE REVIEW

**Comment by tovbinm** [comment]
This change also requires modifying `@frontegg/js`
```
diff --git a/node_modules/@frontegg/react/index.js b/node_modules/@frontegg/react/index.js
index d2199a7..abfb09d 100644
--- a/node_modules/@frontegg/react/index.js
+++ b/node_modules/@frontegg/react/index.js
@@ -239,4 +239,5 @@ exports.Connector = Connector;
 exports.ConnectorHistory = ConnectorHistory;
 exports.FronteggProvider = FronteggProvider;
 exports.useCheckoutDialog = useCheckoutDialog;
+exports.AppHolder = AppHolder.AppHolder;
 //# sourceMappingURL=index.js.map
```

Where can I modify it?

**Comment by frontegg-david** [comment]
What is the purpose of exporting the AppHolder class?
@tovbinm

**Comment by tovbinm** [comment]
@frontegg-david this to allow modifying `appHolder?.options?.metadata` dynamically, e.g. `appHolderMetadata?.navigation?.sso?.visibility` etc.

**Comment by rotemzif1** [comment]
Hey, @tovbinm we are working on a more suitable solution that will help you set metadata directly in our state in a way that will help you to achieve exactly what you need. You will be able to consume a hook to setMetadataState and will be able to easily change it according to the runtime situation. Therefore we will not merge this PR since this solution is a bit hacky. We will provide a new solution in the near future.

**Comment by tovbinm** [comment]
Where is this going to be announced?

**Comment by rotemzif1** [comment]
@tovbinm In our library GitHub changelog for sure, and also we can let you know in our community if that will be helpful for you ?

**Comment by tovbinm** [comment]
Thanks. I will keep an eye on it.

**Pull request closed without merging**
